### ISSUE TITLE
Crashing under Windows 10 1607 build 14393.1358

### ISSUE THREAD

**Issue by lecopoa** [thatsafy/MGSV_SaveManager#4]
Hey.

I'm using the version 2.5.0 and it simply crashes when I select the Saves option. Even if I try to run it as Admin.

I'm attaching the log and config files but I just don't know what else I can say regarding the crash because it just crashes (seemingly) without reason.

https://pastebin.com/YiJtNEjr

users.txt is empty. I believe it is because there's only one user on this Windows.

EDIT:

I was checking the installation folders and I saw that the software uses %programdata% folder. This folder tends to be a mess because of user permissions on Windows 10. Even though I'm Admin I'm having a hard time trying to remove the read-only stat from the folder. I tried to manually type my username on the users.txt and, of course, it won't save because it is set to read-only. I wonder if it is crashing because it can't edit the file.

**Comment by thatsafy** [comment]
Ok, I think I've managed to track down the cause, and it simply was when listing available steam users I forgot to take into account the spaces in the directory path in that particular instance.  
Also the **"users.txt"** will just list the user id's found in the **Steam\\userdata** directory, so if one has multiple steam accounts it is possible to have separate saves for those accounts.  
And also the application should run just fine (after I push the fix update) without admin privileges.
