### ISSUE TITLE
steam installation not found

### ISSUE THREAD

**Issue by challanger244** [thatsafy/MGSV_SaveManager#5]
![image](https://user-images.githubusercontent.com/48139494/77263693-cdad5280-6c90-11ea-89d7-576f00b7c211.png)
i have the game installed under the B drive but the steam exe is correctly located

**Comment by Zer01neDev** [comment]
The tool is shit, he want you to have Steam installation, we just need a tool that allow us to check and edit the save, that's it, in my case, i just want to know the % of completion of my old save.

**Comment by thatsafy** [comment]
The project has been discontinued since 2017 (hence the "discontinued" label on the project page). Closing issue and disabling new issues as well.
